### ISSUE TITLE
Elaho sometimes crashes when navigating to host that is down 

### ISSUE THREAD

**Issue by IdlePhysicist** [pitr/gemini-ios#23] opened 2021-03-12 18:31 UTC
I have noticed with several capsules where the host is down or unreachable that Elaho just crashes after ~60s of "loading". Although sometimes (1/4 times) I get a message reading the following:

```
The operation couldn't be completed.
(Network.NWError error 0.)
```

One host I have noted this with is `artorinix.space`

```
$ host artorinix.space
artorinix.space has address 24.56.122.9
```
Using `amfora` I get the following message, but no crash.

```
Failed to connect to the server: dial
tcp 24.56.122.9:1965: i/o timeout.
```

Otherwise I am _extremely_ happy with the app! Having a clean simple interface I find myself using Gemini & Elaho more and more. Thank you.

**Comment by pitr** [comment] 2021-03-12 22:49
i believe this is a dup of #19 as I am unable to reproduce the crash with the new build. I will be releasing the new version this weekend, having tested it for the last week.

**Comment by pitr** [comment] 2021-03-13 18:17
v1.4 was released into App Store with this fix

**Closed as completed by pitr** 2021-03-13 18:17 UTC
Labels: bug
